name: 'Herbie config'
description: 'A bundle of miscellaneous configuration files, mainly to override default configuration in modules or other settings. '
type: module
core_version_requirement: '^9.4 || ^10'
version: '1.3'
package: Herbie
dependencies:
  - 'entity_usage:entity_usage'
  - 'moderated_content_bulk_publish:moderated_content_bulk_publish'
  - 'replicate_ui:replicate_ui'
